### 1. Crear Dataframe desde archivo .csv

In [1]:
import pandas as pd
import numpy as np 

df = pd.read_csv('/Users/martinhenriquez/Downloads/resumen_resultados_astronautas.csv')

In [2]:
df.info()

#Contamos con 32 registros y 10 columnas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   nombre                  32 non-null     object
 1   edad                    32 non-null     int64
 2   peso                    32 non-null     int64
 3   altura                  32 non-null     int64
 4   evaluacion_fisica       32 non-null     int64
 5   evaluacion_psicologica  32 non-null     int64
 6   evaluacion_adaptativa   32 non-null     int64
 7   evaluacion_medica       32 non-null     int64
 8   anos_experiencia        32 non-null     int64
 9   califica                32 non-null     object
dtypes: int64(8), object(2)
memory usage: 2.6+ KB

### El IMC es una medida importante que nos ayuda a determinar si una persona tiene un peso saludable para poder ser un astronauta. Se calcula siguiendo la formula peso/(estatura^2), donde peso está en kg y estatura en metros.

In [3]:
# Creo una nueva columna con la altura en metros para realizar calculo del IMC 

df["altura_m"] = df["altura"] / 100

In [4]:
#Creo columna IMC con la nueva columna altura_m

df["IMC"] = df["peso"] / (df["altura_m"] ** 2)
df

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,altura_m,IMC
0,Alana Morillo,32,75,180,93,88,78,89,6,Si,1.80,23.148148
1,Fátima Tafalla,27,68,167,82,95,81,87,4,Si,1.67,24.382373
2,Sofía Puig,29,80,185,85,80,90,91,3,Si,1.85,23.374726
3,Valentina Tasis,30,65,175,90,91,85,92,2,No,1.75,21.224490
4,Regina Cicerón,31,76,183,89,87,83,90,7,Si,1.83,22.694019
5,Amaya de la Cruz,26,64,170,80,94,79,86,4,No,1.70,22.145329
6,María Juderías,28,78,182,88,85,87,92,5,Si,1.82,23.547881
7,Perla Alcocer,30,71,168,86,92,82,88,3,No,1.68,25.155896
8,Consuela Arboleda,33,77,188,94,83,89,93,8,Si,1.88,21.785876
9,María José Franco,29,70,175,87,90,80,89,2,No,1.75,22.857143
10,Emanuel Gálvez,27,73,181,84,89,84,87,3,Si,1.81,22.282592
11,Alberto Graciani,28,62,163,81,93,77,85,5,No,1.63,23.335466
12,Patricio Encarnación,30,81,190,93,86,88,91,4,Si,1.90,22.437673
13,Cristóbal Miralles,31,72,174,88,91,86,92,6,No,1.74,23.781213
14,Pablo Cotilla,27,75,178,86,87,85,89,2,Si,1.78,23.671254
15,Pablo Capmany,29,69,171,82,94,80,88,4,No,1.71,23.597004
16,Nicolás Cambeiro,29,68,175,88,90,81,90,2,No,1.75,22.204082
17,Daniel Sánchez,26,63,167,80,93,78,85,4,No,1.67,22.589551
18,Samuel Gálvez,22,74,183,91,91,91,86,3,Si,1.83,22.096808
19,José París,40,68,163,78,85,85,77,8,No,1.63,25.593737
20,Kevin Pareja,27,61,177,85,90,87,79,2,Si,1.77,19.470778
21,Estefania Manzanares,31,79,179,89,82,85,81,5,Si,1.79,24.655910
22,Óliver Fonseca,38,80,164,77,88,90,89,9,No,1.64,29.744200
23,Christopher Berganza,23,70,173,92,93,92,85,1,Si,1.73,23.388687
24,Álvaro Espina,30,76,180,90,84,87,82,4,Si,1.80,23.456790
25,Leonardo Magrina,39,65,171,79,92,90,85,8,No,1.71,22.229062
26,Fernando Gálvez,25,72,168,88,88,89,83,2,Si,1.68,25.510204
27,Sophie González,36,75,176,85,82,84,80,7,No,1.76,24.212293
28,Alexia Gaos,21,69,169,93,94,93,86,0,Si,1.69,24.158818
29,Fátima Varela,33,73,182,91,90,91,88,5,Si,1.82,22.038401
30,Clara Arias,44,63,162,77,87,88,84,11,No,1.62,24.005487
31,Paloma Berganza,28,62,174,87,85,87,78,3,Si,1.74,20.478267

In [5]:
#Agregamos columna promedio_evaluaciones

df['promedio_evaluaciones'] = (df['evaluacion_fisica'] + df['evaluacion_psicologica'] + df['evaluacion_adaptativa'] + df['evaluacion_medica']) / 4

In [6]:
#Nuevo dataframe donde solo iran aquellos que estén dentro del rango de IMC requerido

df2 = df.loc[(df['IMC'] >= 18.5) & (df['IMC'] <= 24.9)]

In [7]:
df2

#Vemos que en el nuevo df hay vacios en el index (7,19,22,26) que corresponden a aquellos con un IMC fuera del rango

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,altura_m,IMC,promedio_evaluaciones
0,Alana Morillo,32,75,180,93,88,78,89,6,Si,1.80,23.148148,87.00
1,Fátima Tafalla,27,68,167,82,95,81,87,4,Si,1.67,24.382373,86.25
2,Sofía Puig,29,80,185,85,80,90,91,3,Si,1.85,23.374726,86.50
3,Valentina Tasis,30,65,175,90,91,85,92,2,No,1.75,21.224490,89.50
4,Regina Cicerón,31,76,183,89,87,83,90,7,Si,1.83,22.694019,87.25
5,Amaya de la Cruz,26,64,170,80,94,79,86,4,No,1.70,22.145329,84.75
6,María Juderías,28,78,182,88,85,87,92,5,Si,1.82,23.547881,88.00
8,Consuela Arboleda,33,77,188,94,83,89,93,8,Si,1.88,21.785876,89.75
9,María José Franco,29,70,175,87,90,80,89,2,No,1.75,22.857143,86.50
10,Emanuel Gálvez,27,73,181,84,89,84,87,3,Si,1.81,22.282592,86.00
11,Alberto Graciani,28,62,163,81,93,77,85,5,No,1.63,23.335466,84.00
12,Patricio Encarnación,30,81,190,93,86,88,91,4,Si,1.90,22.437673,89.50
13,Cristóbal Miralles,31,72,174,88,91,86,92,6,No,1.74,23.781213,89.25
14,Pablo Cotilla,27,75,178,86,87,85,89,2,Si,1.78,23.671254,86.75
15,Pablo Capmany,29,69,171,82,94,80,88,4,No,1.71,23.597004,86.00
16,Nicolás Cambeiro,29,68,175,88,90,81,90,2,No,1.75,22.204082,87.25
17,Daniel Sánchez,26,63,167,80,93,78,85,4,No,1.67,22.589551,84.00
18,Samuel Gálvez,22,74,183,91,91,91,86,3,Si,1.83,22.096808,89.75
20,Kevin Pareja,27,61,177,85,90,87,79,2,Si,1.77,19.470778,85.25
21,Estefania Manzanares,31,79,179,89,82,85,81,5,Si,1.79,24.655910,84.25
23,Christopher Berganza,23,70,173,92,93,92,85,1,Si,1.73,23.388687,90.50
24,Álvaro Espina,30,76,180,90,84,87,82,4,Si,1.80,23.456790,85.75
25,Leonardo Magrina,39,65,171,79,92,90,85,8,No,1.71,22.229062,86.50
27,Sophie González,36,75,176,85,82,84,80,7,No,1.76,24.212293,82.75
28,Alexia Gaos,21,69,169,93,94,93,86,0,Si,1.69,24.158818,91.50
29,Fátima Varela,33,73,182,91,90,91,88,5,Si,1.82,22.038401,90.00
30,Clara Arias,44,63,162,77,87,88,84,11,No,1.62,24.005487,84.00
31,Paloma Berganza,28,62,174,87,85,87,78,3,Si,1.74,20.478267,84.25

In [8]:
#Reset index del nuevo dataframe
df2 = df2.reset_index(drop=True)
df2

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,altura_m,IMC,promedio_evaluaciones
0,Alana Morillo,32,75,180,93,88,78,89,6,Si,1.80,23.148148,87.00
1,Fátima Tafalla,27,68,167,82,95,81,87,4,Si,1.67,24.382373,86.25
2,Sofía Puig,29,80,185,85,80,90,91,3,Si,1.85,23.374726,86.50
3,Valentina Tasis,30,65,175,90,91,85,92,2,No,1.75,21.224490,89.50
4,Regina Cicerón,31,76,183,89,87,83,90,7,Si,1.83,22.694019,87.25
5,Amaya de la Cruz,26,64,170,80,94,79,86,4,No,1.70,22.145329,84.75
6,María Juderías,28,78,182,88,85,87,92,5,Si,1.82,23.547881,88.00
7,Consuela Arboleda,33,77,188,94,83,89,93,8,Si,1.88,21.785876,89.75
8,María José Franco,29,70,175,87,90,80,89,2,No,1.75,22.857143,86.50
9,Emanuel Gálvez,27,73,181,84,89,84,87,3,Si,1.81,22.282592,86.00
10,Alberto Graciani,28,62,163,81,93,77,85,5,No,1.63,23.335466,84.00
11,Patricio Encarnación,30,81,190,93,86,88,91,4,Si,1.90,22.437673,89.50
12,Cristóbal Miralles,31,72,174,88,91,86,92,6,No,1.74,23.781213,89.25
13,Pablo Cotilla,27,75,178,86,87,85,89,2,Si,1.78,23.671254,86.75
14,Pablo Capmany,29,69,171,82,94,80,88,4,No,1.71,23.597004,86.00
15,Nicolás Cambeiro,29,68,175,88,90,81,90,2,No,1.75,22.204082,87.25
16,Daniel Sánchez,26,63,167,80,93,78,85,4,No,1.67,22.589551,84.00
17,Samuel Gálvez,22,74,183,91,91,91,86,3,Si,1.83,22.096808,89.75
18,Kevin Pareja,27,61,177,85,90,87,79,2,Si,1.77,19.470778,85.25
19,Estefania Manzanares,31,79,179,89,82,85,81,5,Si,1.79,24.655910,84.25
20,Christopher Berganza,23,70,173,92,93,92,85,1,Si,1.73,23.388687,90.50
21,Álvaro Espina,30,76,180,90,84,87,82,4,Si,1.80,23.456790,85.75
22,Leonardo Magrina,39,65,171,79,92,90,85,8,No,1.71,22.229062,86.50
23,Sophie González,36,75,176,85,82,84,80,7,No,1.76,24.212293,82.75
24,Alexia Gaos,21,69,169,93,94,93,86,0,Si,1.69,24.158818,91.50
25,Fátima Varela,33,73,182,91,90,91,88,5,Si,1.82,22.038401,90.00
26,Clara Arias,44,63,162,77,87,88,84,11,No,1.62,24.005487,84.00
27,Paloma Berganza,28,62,174,87,85,87,78,3,Si,1.74,20.478267,84.25

In [9]:
# Nuevo dataframe en base al df filtrado segun IMC donde solo iran aquellos con el promedio de evaluaciones requerido
df3 = df2.loc[(df2['promedio_evaluaciones'] >= 87)]

In [10]:
df3

#Vemos que en el nuevo df hay vacios en el index que corresponden a aquellos casos que no cumplen el promedio de evaluaciones

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,altura_m,IMC,promedio_evaluaciones
0,Alana Morillo,32,75,180,93,88,78,89,6,Si,1.80,23.148148,87.00
3,Valentina Tasis,30,65,175,90,91,85,92,2,No,1.75,21.224490,89.50
4,Regina Cicerón,31,76,183,89,87,83,90,7,Si,1.83,22.694019,87.25
6,María Juderías,28,78,182,88,85,87,92,5,Si,1.82,23.547881,88.00
7,Consuela Arboleda,33,77,188,94,83,89,93,8,Si,1.88,21.785876,89.75
11,Patricio Encarnación,30,81,190,93,86,88,91,4,Si,1.90,22.437673,89.50
12,Cristóbal Miralles,31,72,174,88,91,86,92,6,No,1.74,23.781213,89.25
15,Nicolás Cambeiro,29,68,175,88,90,81,90,2,No,1.75,22.204082,87.25
17,Samuel Gálvez,22,74,183,91,91,91,86,3,Si,1.83,22.096808,89.75
20,Christopher Berganza,23,70,173,92,93,92,85,1,Si,1.73,23.388687,90.50
24,Alexia Gaos,21,69,169,93,94,93,86,0,Si,1.69,24.158818,91.50
25,Fátima Varela,33,73,182,91,90,91,88,5,Si,1.82,22.038401,90.00

In [11]:
#reset index del dataframe final 
df3 = df3.reset_index(drop=True)

In [12]:
df3

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,altura_m,IMC,promedio_evaluaciones
0,Alana Morillo,32,75,180,93,88,78,89,6,Si,1.80,23.148148,87.00
1,Valentina Tasis,30,65,175,90,91,85,92,2,No,1.75,21.224490,89.50
2,Regina Cicerón,31,76,183,89,87,83,90,7,Si,1.83,22.694019,87.25
3,María Juderías,28,78,182,88,85,87,92,5,Si,1.82,23.547881,88.00
4,Consuela Arboleda,33,77,188,94,83,89,93,8,Si,1.88,21.785876,89.75
5,Patricio Encarnación,30,81,190,93,86,88,91,4,Si,1.90,22.437673,89.50
6,Cristóbal Miralles,31,72,174,88,91,86,92,6,No,1.74,23.781213,89.25
7,Nicolás Cambeiro,29,68,175,88,90,81,90,2,No,1.75,22.204082,87.25
8,Samuel Gálvez,22,74,183,91,91,91,86,3,Si,1.83,22.096808,89.75
9,Christopher Berganza,23,70,173,92,93,92,85,1,Si,1.73,23.388687,90.50
10,Alexia Gaos,21,69,169,93,94,93,86,0,Si,1.69,24.158818,91.50
11,Fátima Varela,33,73,182,91,90,91,88,5,Si,1.82,22.038401,90.00

In [13]:
#Reemplazamos los valores "No" de la columna 'califica' dentro del mismo Dataframe

df3['califica'].replace("No", "Si", inplace=True)

In [14]:
df3

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,altura_m,IMC,promedio_evaluaciones
0,Alana Morillo,32,75,180,93,88,78,89,6,Si,1.80,23.148148,87.00
1,Valentina Tasis,30,65,175,90,91,85,92,2,Si,1.75,21.224490,89.50
2,Regina Cicerón,31,76,183,89,87,83,90,7,Si,1.83,22.694019,87.25
3,María Juderías,28,78,182,88,85,87,92,5,Si,1.82,23.547881,88.00
4,Consuela Arboleda,33,77,188,94,83,89,93,8,Si,1.88,21.785876,89.75
5,Patricio Encarnación,30,81,190,93,86,88,91,4,Si,1.90,22.437673,89.50
6,Cristóbal Miralles,31,72,174,88,91,86,92,6,Si,1.74,23.781213,89.25
7,Nicolás Cambeiro,29,68,175,88,90,81,90,2,Si,1.75,22.204082,87.25
8,Samuel Gálvez,22,74,183,91,91,91,86,3,Si,1.83,22.096808,89.75
9,Christopher Berganza,23,70,173,92,93,92,85,1,Si,1.73,23.388687,90.50
10,Alexia Gaos,21,69,169,93,94,93,86,0,Si,1.69,24.158818,91.50
11,Fátima Varela,33,73,182,91,90,91,88,5,Si,1.82,22.038401,90.00

In [ ]:
df3.to_csv('astronautas_calificados.csv')